### ISSUE TITLE
Not able to deploy the LRS on Windows 10

### ISSUE THREAD

**Issue by eMelgooG** [vbhayden/adl-lrs-docker#1]
Background:
I'm trying to build a LRS from scratch and right now I'm building the DB (very close to finish). I found this Open Source LRS and I'm trying to deploy it in order to extract the DB Schema to analyze it and compare it with my version. I currently don't have Ubuntu on my machine and I'm running low on space so I thought this Docker alternative would be a great solution. 
So I followed your tutorial step by step but unfortunately I couldn't make it work. I get two errors.
In the PostgreSql container:
```
_Error: Database is uninitialized and superuser password is not specified.

You must specify POSTGRES_PASSWORD to a non-empty value for the

superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".


You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all

connections without a password. This is *not* recommended.


See PostgreSQL documentation about "trust":

https://www.postgresql.org/docs/current/auth-trust.html_
```

And in the Django Web Service container:

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

Also when I try to manually run the Postgres container with this command:

**docker run adl-lrs-docker_postgres POSTGRES_HOST_AUTH_METHOD=trust**  

I get this error: 
`/usr/local/bin/docker-entrypoint.sh: line 315: exec: POSTGRES_HOST_AUTH_METHOD=trust: not found`

**Comment by eMelgooG** [comment]
I was able to start the Postgres by adding this to the docker-compose.yml and run the rebuild.sh again
```
  environment:
       POSTGRES_HOST_AUTH_METHOD: trust
```

I still have this error though: 
`standard_init_linux.go:211: exec user process caused "no such file or directory"`

![image](https://user-images.githubusercontent.com/1024604/96730769-37c0de00-13bf-11eb-8a03-8e3a10cb5d3f.png)


I'm fairly new to Docker, I just started using it today

**Comment by vbhayden** [comment]
Hmmm interesting, I'll take a look at this today.  We had an issue recently where the Postgres image started requiring some auth stuff and misbehaved otherwise.

Thanks for bringing this up!

**Comment by eMelgooG** [comment]
@vbhayden Any update?

**Comment by vbhayden** [comment]
Not sure, long week at work so I admittedly ignored email Friday afternoon up to today.  

I haven't had much success running Docker for Windows in general and my current machines all have VirtualBox, but I'll fiddle with it some tonight.

**Comment by vbhayden** [comment]
Although it looks like there are a few solutions to a similar issue here:
https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

**Comment by eMelgooG** [comment]
I set up the LRS in Ubuntu without docker and it works fine. 
Thank you!
